// Generated by gencpp from file actuators/Vector3.msg
// DO NOT EDIT!


#ifndef ACTUATORS_MESSAGE_VECTOR3_H
#define ACTUATORS_MESSAGE_VECTOR3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuators
{
template <class ContainerAllocator>
struct Vector3_
{
  typedef Vector3_<ContainerAllocator> Type;

  Vector3_()
    : tri()  {
      tri.assign(0.0);
  }
  Vector3_(const ContainerAllocator& _alloc)
    : tri()  {
  (void)_alloc;
      tri.assign(0.0);
  }



   typedef boost::array<float, 3>  _tri_type;
  _tri_type tri;





  typedef boost::shared_ptr< ::actuators::Vector3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuators::Vector3_<ContainerAllocator> const> ConstPtr;

}; // struct Vector3_

typedef ::actuators::Vector3_<std::allocator<void> > Vector3;

typedef boost::shared_ptr< ::actuators::Vector3 > Vector3Ptr;
typedef boost::shared_ptr< ::actuators::Vector3 const> Vector3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuators::Vector3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuators::Vector3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuators::Vector3_<ContainerAllocator1> & lhs, const ::actuators::Vector3_<ContainerAllocator2> & rhs)
{
  return lhs.tri == rhs.tri;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuators::Vector3_<ContainerAllocator1> & lhs, const ::actuators::Vector3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuators

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuators::Vector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuators::Vector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuators::Vector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuators::Vector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuators::Vector3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuators::Vector3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuators::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c49180465985aea8f1b4c8c15017d58";
  }

  static const char* value(const ::actuators::Vector3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c49180465985aeaULL;
  static const uint64_t static_value2 = 0x8f1b4c8c15017d58ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuators::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuators/Vector3";
  }

  static const char* value(const ::actuators::Vector3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuators::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] tri\n"
;
  }

  static const char* value(const ::actuators::Vector3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuators::Vector3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tri);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuators::Vector3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuators::Vector3_<ContainerAllocator>& v)
  {
    s << indent << "tri[]" << std::endl;
    for (size_t i = 0; i < v.tri.size(); ++i)
    {
      s << indent << "  tri[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tri[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORS_MESSAGE_VECTOR3_H
