// Generated by gencpp from file filters_algorithms/path.msg
// DO NOT EDIT!


#ifndef FILTERS_ALGORITHMS_MESSAGE_PATH_H
#define FILTERS_ALGORITHMS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace filters_algorithms
{
template <class ContainerAllocator>
struct path_
{
  typedef path_<ContainerAllocator> Type;

  path_()
    {
    }
  path_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::filters_algorithms::path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::filters_algorithms::path_<ContainerAllocator> const> ConstPtr;

}; // struct path_

typedef ::filters_algorithms::path_<std::allocator<void> > path;

typedef boost::shared_ptr< ::filters_algorithms::path > pathPtr;
typedef boost::shared_ptr< ::filters_algorithms::path const> pathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::filters_algorithms::path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::filters_algorithms::path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace filters_algorithms

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::filters_algorithms::path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::filters_algorithms::path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::filters_algorithms::path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::filters_algorithms::path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::filters_algorithms::path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::filters_algorithms::path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::filters_algorithms::path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::filters_algorithms::path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::filters_algorithms::path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "filters_algorithms/path";
  }

  static const char* value(const ::filters_algorithms::path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::filters_algorithms::path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::filters_algorithms::path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::filters_algorithms::path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::filters_algorithms::path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::filters_algorithms::path_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FILTERS_ALGORITHMS_MESSAGE_PATH_H
